export const config = {
  api: {
    baseUrl: import.meta.env.VITE_BASE_API_URL ?? '',
    endpoints: {
      sessions:    '/api/v1/sessions',
      session:     (id: string) => `/api/v1/sessions/${id}`,
      sessionMessages: (id: string) => `/api/v1/sessions/${id}/messages`,
      chat:        '/api/v1/chat',
      chatAnswer:  '/api/v1/chat/answer',
      skills:      '/api/v1/skills',
      skill:       (name: string) => `/api/v1/skills/${name}`,
      skillRescan: '/api/v1/skills/rescan',
      cronjobs:    '/api/v1/cronjobs',
      cronjob:     (id: string) => `/api/v1/cronjobs/${id}`,
      dashboard:   '/api/v1/dashboard',
      auditLog:    '/api/v1/audit-log',
      settings:    '/api/v1/settings',
      health:        '/actuator/health',
      models:        '/api/v1/settings/models',
      modelsAll:     '/api/v1/settings/models/all',
      providers:     '/api/v1/settings/providers',
      modelsRefresh: '/api/v1/settings/models/refresh',
      doctor:        '/api/v1/settings/doctor',
    },
  },
  routes: {
    chat:        '/chat',
    chatSession: (id: string) => `/chat/${id}`,
    skills:      '/skills',
    skillNew:    '/skills/new',
    skill:       (name: string) => `/skills/${name}`,
    cronjobs:    '/cronjobs',
    dashboard:   '/dashboard',
    auditLog:    '/audit-log',
    settings:    '/settings',
    login:       '/login',
    onboard:     '/onboard',
  },
  session: {
    tokenKey: 'ec_auth_token',
  },
  ui: {
    maxNotifications:    5,
    notificationTimeout: 5000,
    errorTimeout:        7000,
    sessionListLimit:    50,
    maxFileUploadBytes:  10 * 1024 * 1024,
  },
  logging: {
    level: (import.meta.env.DEV ? 'debug' : 'info') as 'debug' | 'info',
  },
} as const
