# curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent"
#  -H "x-goog-api-key: $GEMINI_API_KEY"
#  -H 'Content-Type: application/json'
#  -X POST
#  -d '{
#    "contents": [
#      {
#        "parts": [
#          {
#            "text": "Explain how AI works in a few words"
#          }
#        ]
#      }
#    ]
#  }'
POST https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
x-goog-api-key: $GEMINI_API_KEY
Content-Type: application/json

{
  "contents": [
    {
      "parts": [
        {
          "text": "Explain how AI works in a few words"
        }
      ]
    }
  ]
}

###

